[package]
name = "arrow-udf-python"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/risingwavelabs/arrow-udf"
keywords = ["arrow", "udf", "python"]
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1"
arrow-array = "50"
arrow-ipc = "50"
arrow-schema = "50"
lazy_static = "1"
pyo3 = { version = "0.20", features = ["auto-initialize"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wlr-libpy = { git = "https://github.com/vmware-labs/webassembly-language-runtimes.git" }

[build-dependencies]
wlr-libpy = { git = "https://github.com/vmware-labs/webassembly-language-runtimes.git", features = [
    "build",
] }

[dev-dependencies]
arrow-cast = { version = "50", features = ["prettyprint"] }
