[package]
name = "arrow-udf-js"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
arrow-array = "49"
arrow-schema = "49"
rquickjs = { version = "0.4", features = ["parallel"] }

[dev-dependencies]
arrow-cast = { version = "49", features = ["prettyprint"] }
