[package]
name = "arrow-udf-wasm"
version = "0.1.0"
edition = "2021"
description = "WebAssembly runtime for Arrow UDFs."
repository = "https://github.com/risingwavelabs/arrow-udf"
keywords = ["arrow", "udf", "wasm"]
categories = ["wasm"]
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
arrow-array = "49"
arrow-ipc = "49"
arrow-schema = "49"
base64 = "0.21"
lazy_static = "1"
wasmtime = "16"
wasmtime-wasi = "16"

[dev-dependencies]
arrow-arith = "49"
arrow-cast = { version = "49", features = ["prettyprint"] }
arrow-udf-python = { path = "../arrow-udf-python" }
arrow-udf-python-wasm = { path = "../arrow-udf-python-wasm" }
criterion = "0.5"

[[bench]]
name = "wasm"
harness = false
