[package]
name = "arrow-udf"
version = "0.1.0"
edition = "2021"
description = "User-defined function framework for arrow-rs."
repository = "https://github.com/risingwavelabs/arrow-udf"
keywords = ["arrow", "udf"]
categories = ["wasm"]
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
global_registry = ["linkme", "lazy_static"]

[dependencies]
arrow-arith = "49"
arrow-array = "49"
arrow-buffer = "49"
arrow-data = "49"
arrow-ipc = "49"
arrow-schema = "49"
arrow-udf-macros = { version = "0.1.0", path = "../arrow-udf-macros" }
chrono = { version = "0.4", default-features = false }
itertools = "0.12"
lazy_static = { version = "1", optional = true }
linkme = { version = "0.3", optional = true }
rust_decimal = "1"
serde_json = "1"

[dev-dependencies]
arrow-cast = { version = "49", features = ["prettyprint"] }
